name: Build & Push Docker Image

on:
  workflow_call:
    inputs:
      component:
        description: "Flyte Go component"
        required: true
        type: string
    secrets:
      FLYTE_BOT_PAT:
        required: true
jobs:
  upgrade-component:
    name: Update ${{ inputs.component }} version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Update release
        run: |
          if [[ ${{ inputs.component }} == "boilerplate" ]]
          then
            make update_boilerplate
          else
            VERSION=$(curl --silent "https://api.github.com/repos/flyteorg/${{ inputs.component }}/releases/latest" | jq -r .tag_name)
            go get -u github.com/flyteorg/${{ inputs.component }}@$VERSION
          fi
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.FLYTE_BOT_PAT }}
          commit-message: Update ${{ inputs.component }} version
          committer: Flyte-Bot <admin@flyte.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: flyte-bot-update-${{ inputs.component }}
          delete-branch: true
          title: "Update ${{ inputs.component }} version"
          body: |
            Update ${{ inputs.component }} version
            - Auto-generated by [flyte-bot]
          labels: |
            ${{ inputs.component }}
          team-reviewers: |
            owners
            maintainers
          draft: false
